In [15]:
with open("/home/adam/Documents/repos/shakespeare/data/tinyshakespeare.txt", 'r', encoding='utf-8') as f:
    text = f.read()

print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [16]:
chars = sorted(list(set(text)))
chars

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [17]:
len(chars)

65

In [18]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

In [19]:
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [20]:
type(encode)

function

In [21]:
encoded_text = encode("test")
print(encode("test"))

[58, 43, 57, 58]


In [22]:
decode(encoded_text)

'test'

In [23]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
# print(data[:1000])

torch.Size([1115394]) torch.int64


In [24]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [25]:
# chunk size
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [26]:
arr = [[1],[1],[1],[1],[1]],[[1],[3],[3],[3],[1]]

In [27]:
arr

([[1], [1], [1], [1], [1]], [[1], [3], [3], [3], [1]])

In [30]:
import numpy
# arr.
numpy.array(arr)

array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [3],
        [3],
        [3],
        [1]]])

In [33]:
numpy.transpose(arr)

array([[[1, 1],
        [1, 3],
        [1, 3],
        [1, 3],
        [1, 1]]])

BEGIN MODULES


In [1]:
import model
dataloader = model.DataLoader()
dataloader.tiny()
dataloader.data[:100]

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'

In [2]:
dataloader.complete()
dataloader.data[:100]

'\ufeffThe Project Gutenberg eBook of The Complete Works of William Shakespeare, by William Shakespeare\n\nT'